[2023-04-05T14:15:08.935096+00:00 INFO] [plan:194] ################################################################################
[2023-04-05T14:15:08.935288+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-05T14:15:08.935532+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T14:15:09.337262+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T14:15:09.337453+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T14:15:09.337597+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-05T14:15:09.337677+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T14:15:09.337751+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T14:15:09.337819+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T14:15:09.353100+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-05T14:15:09.353201+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-05T14:15:09.353263+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-05T14:15:09.353342+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T14:15:09.353403+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T14:15:09.353521+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T14:15:09.353596+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T14:15:09.353655+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T14:15:09.353718+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-05T14:15:09.353838+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-05T14:15:09.355932+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T14:15:09.356052+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T14:15:09.356219+00:00 DEBUG] [__init__:41] Missing URL for safeguard/precheck call.
[2023-04-05T14:15:09.356301+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-05T14:15:09.356368+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-05T14:15:09.356439+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-04-05T14:15:09.356640+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-05T14:15:09.770659+00:00 INFO] [experiment:192] Reliably execution: c60d8554-58c3-44cc-8cd6-c9c739552930
[2023-04-05T14:15:10.077261+00:00 DEBUG] [experiment:552] Sending plan '1ed65644-d3ce-4578-bbf7-c96060cdfb08' status: running
[2023-04-05T14:15:10.980719+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-05T14:15:10.980860+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-05T14:15:10.982349+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-05T14:15:10.982837+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-05T14:15:10.983335+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-05T14:15:10.983852+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T14:15:10.984680+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T14:15:10.985432+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-05T14:15:10.986037+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-05T14:15:10.986155+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-05T14:15:10.986238+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-05T14:15:10.986331+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-05T14:15:10.986416+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-05T14:15:10.987716+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-05T14:15:10.988353+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-05T14:15:10.988890+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-05T14:15:10.989377+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-05T14:15:10.989929+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T14:15:10.990440+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_hypothesis_control'
[2023-04-05T14:15:10.990933+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-05T14:15:10.991357+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-05T14:15:10.991818+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T14:15:10.992274+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_activity_control'
[2023-04-05T14:15:10.992778+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-05T14:15:11.504179+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-05T14:15:11.849799+00:00 DEBUG] [activity:235]   => succeeded with '0.257528'
[2023-04-05T14:15:12.253007+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-05T14:15:12.253255+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-05T14:15:12.253344+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T14:15:12.253432+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_activity_control'
[2023-04-05T14:15:12.253560+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-05T14:15:12.253693+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-05T14:15:12.253935+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-05T14:15:12.254082+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-05T14:15:12.254217+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-05T14:15:12.254297+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T14:15:12.254375+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_hypothesis_control'
[2023-04-05T14:15:12.254473+00:00 CRITICAL] [run:601] Steady state probe 'measure-endpoint-response-time' is not in the given tolerance so failing this experiment
[2023-04-05T14:15:12.254565+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-05T14:15:12.254677+00:00 INFO] [run:943] Let's rollback...
[2023-04-05T14:15:12.254783+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-05T14:15:12.254866+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-05T14:15:12.254941+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-05T14:15:12.255033+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-05T14:15:12.255126+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-05T14:15:12.255220+00:00 INFO] [run:510] Experiment ended with status: deviated
[2023-04-05T14:15:12.255293+00:00 INFO] [run:512] The steady-state has deviated, a weakness may have been discovered
[2023-04-05T14:15:12.255367+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-05T14:15:12.255442+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-05T14:15:12.255510+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T14:15:12.255580+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_experiment_control'
[2023-04-05T14:15:12.255647+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-05T14:15:12.255721+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-05T14:15:12.255795+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-05T14:15:12.255866+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T14:15:12.255938+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'cleanup_control'
[2023-04-05T14:15:12.256017+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-05T14:15:12.496376+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-05T14:15:12.905066+00:00 DEBUG] [experiment:552] Sending plan '1ed65644-d3ce-4578-bbf7-c96060cdfb08' status: completed
[2023-04-05T14:15:13.715397+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-05T14:15:13.715648+00:00 DEBUG] [caching:42] Clearing activities cache
